### ISSUE TITLE
The Antialiasing Operation of nvdiffrast

### ISSUE THREAD

**Issue by JiejiangWu** [sicxu/Deep3DFaceRecon_pytorch#100]
Thanks for sharing the nice work!
After reading the code, I have some questions about the nvdiffrast. As you said in the nvdiffrast.py, you don't use the Antialiasing Operation of nvdiffrast. However, after checking the nvdiffrast's official doc, I found it said that "the real goal is to obtain gradients w.r.t. vertex positions related to occlusion, visibility, and coverage". 

So, is it right that the rendered image-related losses (e.g., the perceptual loss) has no gradient w.r.t. to the id_coeff and the exp_coeff? So are these two coefficients only optimized by the landmark loss in the training?

Also, I wonder if you have tested the Antialiasing? Will it make the performance worse or better?

**Comment by sicxu** [comment]
I have not tested antialiasing. Antialiasing is effective for boundary part, which is essential for something like silhouette loss. For  our training pipeline, we believe that whether the antialiasing step is used or not will make little difference.

**Comment by JiejiangWu** [comment]
Thanks for your reply. After checking the nvdiffrast's doc again, I think you are right.
Antialiasing is necessary when some silhouette-related losses are used. For the pixel color loss and perceptual loss, the gradient can be flowed correctly to vertex_norm, further to the vertex position, even without the antialiasing process.
Thanks again for the opening source of this excellent job.
