### ISSUE TITLE
each output mesh has different vertex ID's 

### ISSUE THREAD

**Issue by adevra** [sicxu/Deep3DFaceRecon_pytorch#103]
Just came across this issue while I was blending different results in Maya,
vertex count is the same in each mesh and thats expected, 
but vertex order is totally different so I had to reorder vertices and transfer VID to other meshes.

Is it possible to get same vertex id's everytime?

**Comment by sicxu** [comment]
This is caused by Trimesh. If we change the process flag to false, it should be the same every time.

**Comment by adevra** [comment]
> This is caused by Trimesh. If we change the process flag to false, it should be the same every time.

This saved a lot of time, thanks
