### ISSUE TITLE
util/BBRegressorParam_r.mat is obtained

### ISSUE THREAD

**Issue by LY-Donkey-Burger** [sicxu/Deep3DFaceRecon_pytorch#104]
Hi，I want to change the number of keypoints, so I want to know how util/BBRegressorParam_r.mat is obtained, can you help me?

**Comment by sicxu** [comment]
BBRegressorParam_r.mat is used to transform 5 keypoints to crop parameters (kind of a hack way).  It has nothing to do with the number of keypoints.
