### ISSUE TITLE
remove link to deprecated nvdiffrast version?

### ISSUE THREAD

**Issue by s-laine** [sicxu/Deep3DFaceRecon_pytorch#108]
Hi, developer of nvdiffrast here. It looks like the Deep3DFaceRecon_pytorch repo points to a really old version of nvdiffrast from March 2021. That link should probably be removed so that nobody installs that version by accident, e.g., via a recursive git clone.

Also, the current version of nvdiffrast includes a Cuda-based rasterizer that doesn't require OpenGL. You may want to consider switching to that by default, as setting up OpenGL can be tricky on some platforms.

**Comment by sicxu** [comment]
Thanks for your suggestion, I have removed the submodule linked to the old nvdiffrast version.  Everyone now can just follow the instruction to git clone the latest nvdiffrast for installation.

**Comment by sicxu** [comment]
I read the latest documentation, I wanna know if we want to switch to  Cuda-based rasterizer, do we just need to replace the context creator from RasterizeGLContext to RasterizeCudaContext?

**Comment by s-laine** [comment]
Yes, that is all it takes.

**Comment by sicxu** [comment]
I have updated the code and README for easy switch, Thanks for your suggestion.

**Comment by WarmCongee** [comment]
Hello, this is a very good work. Your work has been widely used in the field of Audio-driven Talking Head Generation this year to test an indicator called E-FID.  "EMO: Emote Portrait Alive - Generating Expressive Portrait Videos with Audio2Video Diffusion Model under Weak Conditions"

When I used this repository to test this indicator, I found an error that may occur during configuration after Jun 30, 2023.

There are three lines of commands in the repository's README.md: 
```
git clone https://github.com/NVlabs/nvdiffrast
cd nvdiffrast
pip install . 
```
The README was updated on May 26, 2023, when the repository link pointed to nvdiffrast version 3.0.0. Now that the nvdiffrast repository has been updated, using other environments originally specified in the repository in combination with nvdiffrast will cause errors in compiling nvdiffrast_plugin.

Therefore, the corresponding nvdiffrast version should be strictly specified in the README. I will then submit a pull request. You can also verify the problem yourself and merge the request
