### ISSUE TITLE
How to get facemodel_info.mat?

### ISSUE THREAD

**Issue by LY-Donkey-Burger** [sicxu/Deep3DFaceRecon_pytorch#110]
12/5000 
Hi, your work is fantastic. I want to reconstruct the facemodel without clipping. In the process of changing, I found that there are skinmask and point_buf parameters in facemodel_info.mat, but these two parameters are based on the clipping model parameters. I don't know how to get these two parameters of the facemodel without cropping, can you provide the facemodel_info.mat of the model without cropping or can you tell me how to get these two parameters?

**Comment by wengjincheng** [comment]
HI @LY-Donkey-Burger  Have you got the point_buf?

**Comment by yuchen814** [comment]
I need help too.

**Comment by WangXuan2401** [comment]
> 12/5000 Hi, your work is fantastic. I want to reconstruct the facemodel without clipping. In the process of changing, I found that there are skinmask and point_buf parameters in facemodel_info.mat, but these two parameters are based on the clipping model parameters. I don't know how to get these two parameters of the facemodel without cropping, can you provide the facemodel_info.mat of the model without cropping or can you tell me how to get these two parameters?

hello ! I really need your help to get the point_buf and skin_mask params in facemodel_info.mat. Could u provide me some suggestions?
thank u very much!

**Comment by yuchen814** [comment]
> 

point_ Buf is the eight points related to the triangle, which can be obtained through the tri of the bfm model. skin_ mask is the skin area that has been reserved in advance. I think the rest is set to 0 or 1.
