### ISSUE TITLE
pytorch3d instead of nvdiffrast

### ISSUE THREAD

**Issue by jonilaserson** [sicxu/Deep3DFaceRecon_pytorch#12]
The nvdiffrast renderer has a very restrictive license policy which prevents using this code for anything but research (unlike in the TF repo). Is there a plan to add a support for pytorch3d or any other alternative differentiable renderer with a more permissive license?

**Comment by haoxurt** [comment]
> available

Hi，according to your experience, if I change nvdiffrast with pytorch3d, will it train successfully?   My sever is centos and it fails to run nvdiffrast.

**Comment by haoxurt** [comment]
> Hi, this repository is mainly for research purpose so we do not consider the license issue of nvdiffrast. Currently we don't have a plan to add other differentiable renderer to this repo. We may consider it in the future when available.

Hi，according to your experience, if I change nvdiffrast with pytorch3d, will it train successfully?   My sever is centos and it fails to run nvdiffrast.

**Comment by YuDeng** [comment]
Pytorch3d should also give reasonable results. The rendering time might be slower than nvdiffrast though.

**Comment by ryanhe312** [comment]
> 
> 
> The nvdiffrast renderer has a very restrictive license policy which prevents using this code for anything but research (unlike in the TF repo). Is there a plan to add a support for pytorch3d or any other alternative differentiable renderer with a more permissive license?

The pytorch3d-compatible modification can be found at https://github.com/ryanhe312/Deep3DFaceRecon_pytorch. Only the nvdiffrast.py is edited. It can render demo images correctly with pytorch3d 0.5.0.

**Comment by arstropica** [comment]
@ryanhe312 Does it require opengl 4.4 +?

**Comment by ryanhe312** [comment]
> @ryanhe312 Does it require opengl 4.4 +?

No, i only have opengl 1.0. Pytorch3d can run without opengl support.

**Comment by sicxu** [comment]
> > The nvdiffrast renderer has a very restrictive license policy which prevents using this code for anything but research (unlike in the TF repo). Is there a plan to add a support for pytorch3d or any other alternative differentiable renderer with a more permissive license?
> 
> The pytorch3d-compatible modification can be found at https://github.com/ryanhe312/Deep3DFaceRecon_pytorch. Only the nvdiffrast.py is edited. It can render demo images correctly with pytorch3d 0.5.0.

Thanks for your implementation. The backward performance of these two renderers may not be the same. If only for test purpose (forward), it would be ok to replace nvdiffrast with the rasterizer of pytorch3d.

**Comment by xingmimfl** [comment]
I update two scripts based on ryanhe312's work, and now it can train using pytorch3d. https://github.com/xingmimfl/Deep3DFaceRecon_pytorch

**Comment by jonilaserson** [comment]
This is awesome!  Thank you @ryanhe312 and @xingmimfl !

How does the pytorch3d trained model compare to the original?

**Comment by matteopantano** [comment]
> I update two scripts based on ryanhe312's work, and now it can train using pytorch3d. https://github.com/xingmimfl/Deep3DFaceRecon_pytorch

Thanks @xingmimfl , can you add MIT license as the original repo? https://github.com/sicxu/Deep3DFaceRecon_pytorch/issues/58

**Comment by luigi-bar** [comment]
@ryanhe312 do you know if your  pytorch3d version can run without gpu? I have tried with no success, but maybe you have some hints for me to try :-) 
Many thanks!
