### ISSUE TITLE
May I know how to solve this problem or is it cause by the Cuda version or library?

### ISSUE THREAD

**Issue by lingleong981130** [sicxu/Deep3DFaceRecon_pytorch#121]
File "/home/ling/Desktop/Deep3DFaceRecon_pytorch/util/preprocess.py", line 195, in align_img
    trans_params = np.array([w0, h0, s, t[0], t[1]])
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

**Comment by luchaoqi** [comment]
Same error

**Comment by kashyap32** [comment]
@luchaoqi Thanks, It worked :)
