### ISSUE TITLE
About Quantitative Evaluation Code

### ISSUE THREAD

**Issue by WangXuan2401** [sicxu/Deep3DFaceRecon_pytorch#125]
Dear author, thank you a lot for your great work.  I am very interested in this  work rrecently. But getting the **shape reconstruction error** is the biggest barrier, which I found really difficult to solve.

Could you be nice to share the evaluation code ? Here is my email address yzhong14@163.com

Thank you for your attention!

**Comment by lizian1611** [comment]
> 亲爱的作者，非常感谢您的出色工作。我最近对这项工作很感兴趣。但是得到**形状重建误差**是最大的障碍，我发现很难解决。
> 
> 能否分享一下评估代码？这是我的邮箱[yzhong14@163.com](mailto:yzhong14@163.com)
> 
> 感谢您的关注！
How do you calculate the ID metric, can you share your thoughts? My email is lza1611@163.com.
