### ISSUE TITLE
How can I generate the example.gif

### ISSUE THREAD

**Issue by li-fang** [sicxu/Deep3DFaceRecon_pytorch#13]
Hi, I wonder how can I render a video with preset camera motion? Just like what you did in the example.gif.

Also, is there a way to extract texture/material file from the obj file?

Thanks in advance!

**Comment by YuDeng** [comment]
The obj file only records vertex color information so there is no extra texture map or material info.

To render a video using custom camera motion, you can manually set face rotations and translations in https://github.com/sicxu/Deep3DFaceRecon_pytorch/blob/73d491102af6731bded9ae6b3cc7466c3b2e9e48/models/bfm.py#L274
Then you can send the output to the renderer defined here:
https://github.com/sicxu/Deep3DFaceRecon_pytorch/blob/73d491102af6731bded9ae6b3cc7466c3b2e9e48/models/facerecon_model.py#L99

The renderer will give you the face image with expected pose.

**Comment by li-fang** [comment]
Thanks for your kind reply! I'll try it.
