### ISSUE TITLE
关于point_buf

### ISSUE THREAD

**Issue by Joel18241096** [sicxu/Deep3DFaceRecon_pytorch#132]
您好，首先十分感激您的工作，读完您的代码后我受益匪浅。
关于point_buf，我注意到这代表每一个三维顶点是哪几个三角面片的顶点，但是，您在有的地方另其部分值等于70798，并且在法向量计算时让这些索引对应的法向量为零向量。这是否意味着：数万个顶点中只有一部分对应了八个三角形，存在一部分顶点只能对应四个三角形，但您为了能够利用torch的矩阵运算特性，特意把他们都补为了八个三角形索引，同时由于零向量的存在，在计算只对应四个三角形的顶点时，补充的索引并不会对最终结果产生影响？
我现在正在基于您的代码生成53215个顶点对应的point_buf，这个信息对我十分重要，谢谢您花时间阅读我的问题！

**Comment by sicxu** [comment]
Yes, you are right. The point_buf is exactly as your described. You can take the following code as a reference.
```
def get_point_buf(verts, faces, max_cnt=8):
    v_num = verts.shape[0]
    max_faces = faces.shape[0]
    v_cnt_table = np.zeros(v_num).astype(np.int32)
    point_buf = np.zeros([v_num, max_cnt]).astype(np.int32) + max_faces
    for i, f in enumerate(faces):
        for j in range(len(f)):
            point_buf[f[j]][v_cnt_table[f[j]]] = i
            v_cnt_table[f[j]] += 1
    return point_buf
```
