### ISSUE TITLE
Segmentation fault (core dumped) with nvdiffrast

### ISSUE THREAD

**Issue by TimmmYang** [sicxu/Deep3DFaceRecon_pytorch#14]
Hello, 
I had such bug when I tried to inference some examples using ```test.py```. The location of the bug is in ```nvdiffrast.py```, line 57:
```python
if self.glctx is None:
    self.glctx = dr.RasterizeGLContext(device=device)
    print("create glctx on device cuda:%d"%device.index)
```
My environment is Ubuntu 18.04, torch=1.6.0, CUDA=11.4, Driver Version=470.57.02

**Comment by YuDeng** [comment]
Did you correctly install OpenGL libraries listed in [nvdiffrast dockerfile](https://github.com/NVlabs/nvdiffrast/blob/main/docker/Dockerfile) ?

**Comment by TimmmYang** [comment]
Yes, OpenGL is installed. I checked my CUDA version and found that it's 10.2 not 11.0 because of the multiple CUDA environments I had. I changed the CUDA version to 11.0 and the problem was solved. I am grateful for the reply. Thanks.

**Comment by YuDeng** [comment]
Okay. I will close this issue then.
