### ISSUE TITLE
about eye close

### ISSUE THREAD

**Issue by xLuge** [sicxu/Deep3DFaceRecon_pytorch#142]
hi，recent update shows better results with eye closed，but single eye closed still bad. any some way to improve？

**Comment by sicxu** [comment]
Thanks for your interests. This update is kind of a easy try to resolve closed-eye issue, we didn't collect single eye closed images in purpose. 
In our experience,  data is critical for expression recovery. As we can see, with only a small but relevant dataset such as 2k images of eyes closed, eye-closed issue can be alleviated. Therefore, collecting specific data and adding appropriate constraints can be a simple and effective method to improve expression recovery.
