### ISSUE TITLE
How to use Arcface to recognize the reconstructed 3d face ?

### ISSUE THREAD

**Issue by gudufengzhongyipilang** [sicxu/Deep3DFaceRecon_pytorch#15]
Thanks for your work, it's very helpful for 3d face recognition. 
The question is that how can i use the Arcface work to recognize a 3d face. There's no related content in the `README` file.

**Comment by sicxu** [comment]
Perhaps your can refer to these lines?
https://github.com/sicxu/Deep3DFaceRecon_pytorch/blob/73d491102af6731bded9ae6b3cc7466c3b2e9e48/models/facerecon_model.py#L152-L154
