### ISSUE TITLE
parameters of render  z_far and z_near

### ISSUE THREAD

**Issue by haoxurt** [sicxu/Deep3DFaceRecon_pytorch#16]
Hi, I noticed that the z_far and z_near is 5 and 15 in the pytorch version.However, the near_clip is 0.01 and far_clip is  50.0 in the tensorflow version.  I wonder why  there is such a difference？

**Comment by YuDeng** [comment]
The original wider range is unnecessary in our case where faces are located with a distance of 10 to the camera, so we change them to 5 and 15 respectively.
