### ISSUE TITLE
visualize the face mesh without texture and color

### ISSUE THREAD

**Issue by chenhao-user** [sicxu/Deep3DFaceRecon_pytorch#163]
Hi! I'd like to know how to generate this kind of facial image below?
![image](https://github.com/sicxu/Deep3DFaceRecon_pytorch/assets/77375989/dd58fe2d-0644-434e-b4e3-2864a9ad6f76)
Based on my own understanding, I set the illumination to 1 in the compute_color function without multiplying it by the texture parameter. I made the following modification. 
```
def compute_color(self, face_texture, face_norm, `gamma):
        gamma = torch.ones_like(gamma)
        .....
        face_color = torch.cat([r, g, b], dim=-1)
        .....
```
However, the results of this change were not satisfactory. One of the results is as follows：
![image](https://github.com/sicxu/Deep3DFaceRecon_pytorch/assets/77375989/cea09bdd-5b68-4d9e-a1e1-7e659fc13b86)

**Comment by harlanhong** [comment]
Hi, do you figure out this problem?

**Comment by chenhao-user** [comment]
I seem to have operated like this before, where 0.5 and 0.1 are values I tried out myself, but of course, you can also try other values.
`# face_texture = torch.full_like(face_texture, 0.5)
# face_norm = self.compute_norm(face_shape)
# face_norm_roted = face_norm @ rotation
# face_gamma = torch.full_like(coef_dict['gamma'], 0.1)
# face_color = self.compute_color(face_texture, face_norm_roted, face_gamma)`
