### ISSUE TITLE
Would you release C-Net model?

### ISSUE THREAD

**Issue by xjcvip007** [sicxu/Deep3DFaceRecon_pytorch#17]
Thank you for your amazing job~ Would you have plan to release the C-Net model weight or training script?

**Comment by YuDeng** [comment]
Hi, currently we do not have a plan for the C-Net part. In fact, C-Net only provides minor improvement upon the naive average scheme for multi-image reconstruction.

**Comment by xjcvip007** [comment]
Thank you for your quick reply~

**Comment by icedpanda** [comment]
Hi @YuDeng , Thank you for sharing your great work.

I'm just new to this area. How can I do model inferencing for the multi-image case? If you could provide some example code would be much appreciated.

Thanks
