### ISSUE TITLE
Open mouth

### ISSUE THREAD

**Issue by nebis-software** [sicxu/Deep3DFaceRecon_pytorch#170]
Hi,
   many thanks for the very nice work! A (hopefully) quick question: if I process a photo of a smiling subject, I get a .obj model with the mouth open, and that is correct. Is there any way (and/or external tools) to close the mouth? having no teeth models look quite odd, see attached

Thanks!!
![image](https://github.com/sicxu/Deep3DFaceRecon_pytorch/assets/132885313/4c71662d-e91f-47ee-9197-e867214554c3)

**Comment by sicxu** [comment]
The most simple way is to disable the exp part by removing the exp_part in the following line. 
https://github.com/sicxu/Deep3DFaceRecon_pytorch/blob/b9e6fa89ea1566bb9ec27922f6f5d87c34b4b261/models/bfm.py#L98

**Comment by nebis-software** [comment]
Works nicely, thanks!
