### ISSUE TITLE
A little confusion about mask used for computing feat loss

### ISSUE THREAD

**Issue by chenerg** [sicxu/Deep3DFaceRecon_pytorch#171]
https://github.com/sicxu/Deep3DFaceRecon_pytorch/blob/b9e6fa89ea1566bb9ec27922f6f5d87c34b4b261/models/facerecon_model.py#L154C57-L154C57 

I think here` self.trans_m` should be `trans_m` to use the same transformation matrix when computing face feature.

**Comment by sicxu** [comment]
For real image, we have precomputed the transform matrix using ground-truth landmarks, so we use the self.trans_m for real image feature extraction directly. For predicted faces, we have two options. We can utilize the predicted facial landmarks to calculate the matrix or we can simply use the predefined one.
