### ISSUE TITLE
请问 生成的3D人脸是如何贴回到原图片中的

### ISSUE THREAD

**Issue by madgnot** [sicxu/Deep3DFaceRecon_pytorch#19]
如何将生成的人脸贴回去
![image](https://user-images.githubusercontent.com/84372551/131643148-f62d77b4-2138-44bc-b02b-85f403892a64.png)

**Comment by YuDeng** [comment]
Hi, 根据[inference](https://github.com/sicxu/Deep3DFaceRecon_pytorch#inference-with-a-pre-trained-model)部分的说明进行操作，会自动生成贴回原图的图片。

**Comment by 1151537695** [comment]
在compute_visuals()这个函数中，将得到的渲染人脸覆盖在原图上就行了

**Comment by madgnot** [comment]
能不能在代码级别做出一些解释

**Comment by madgnot** [comment]
> Hi, 根据[inference](https://github.com/sicxu/Deep3DFaceRecon_pytorch#inference-with-a-pre-trained-model)部分的说明进行操作，会自动生成贴回原图的图片。

能不能麻烦你在代码级别做出指导

**Comment by madgnot** [comment]
> 在compute_visuals()这个函数中，将得到的渲染人脸覆盖在原图上就行了

这个函数里面啥也没写，具体怎么贴回去呢？

**Comment by 1151537695** [comment]
facerecon_model这个文件下的compute_visuals函数...顺便建议看一下继承啥的
