### ISSUE TITLE
[F glutil.cpp:338] eglInitialize() failed Aborted (core dumped)

### ISSUE THREAD

**Issue by yuzhou164** [sicxu/Deep3DFaceRecon_pytorch#2]
Greate work. I'm having a problem on running the inference code.
Firstly, I meeted the problem of **fatal error: EGL/egl.h: No such file or directory**. 
I installed a package by **apt-get install libegl1-mesa-dev**. 
Then I met another problem 
**[F glutil.cpp:338] eglInitialize() failed
Aborted (core dumped).**, 
Do you have any ideas how to fix this problem?
![企业微信截图_1626788788701](https://user-images.githubusercontent.com/2318194/126335100-2654b72c-5ade-4431-a6c4-d1a30458d6ad.png)
![企业微信截图_16267887991412](https://user-images.githubusercontent.com/2318194/126335113-d1dafb2a-504b-4a32-b835-a83b15af9cbd.png)
![企业微信截图_1626788741329](https://user-images.githubusercontent.com/2318194/126335125-c8ee6b94-863f-46dc-a6a0-4dcabbe89d6f.png)

My Linux Environment:
cudnn: 7.6
cuda: 10.2
python :3.6
pytorch:1.6.0

**Comment by YuDeng** [comment]
Hi, the problem seems to be caused by some OpenGL related libraries required by nvdiffrast. Could you try to follow the [Dockerfile](https://github.com/NVlabs/nvdiffrast/blob/main/docker/Dockerfile) provided by nvdiffrast to install the dependencies and re-install nvdiffrast to see if it works?

**Comment by yuzhou164** [comment]
Thank for your answering, the problem has been solved. You can close this issue.

**Comment by YuDeng** [comment]
Hi, glad to hear that you have solved the issue. Could you post the extra dependencies you have installed? 
We can add them to our installation instruction and help newcomers to build the environment from scratch.

**Comment by yuzhou164** [comment]
[nvdiffrast.zip](https://github.com/sicxu/Deep3DFaceRecon_pytorch/files/6854847/nvdiffrast.zip)
Hi, This ZIP package includes a dockerfile with requirement.txt for this Deep3DFaceRecon_pytorch project. 
The command to build the environment is  `docker build -f docker/Dockerfile -t name:tagname .`    
One thing needs attention is that the version correspondence between version **Cuda** and version **Nvidia Driver** .  Please refer The [website](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html)

**Comment by YuDeng** [comment]
Okay. Thanks for your kind reply.

**Comment by haoxurt** [comment]
@YuDeng Hi, I also encountered `[F glutil.cpp:338] eglInitialize() failed Aborted `. My system is centos. DId you run the code in the centos?  CentOS is reportedly problematic when using nvdiffrast.

**Comment by haoxurt** [comment]
@yuzhou164 Hi, could you share your version Cuda and version Nvidia Drive?

**Comment by punkoffice** [comment]
Do I have to run the docker environment?  What is the command to do that?  Sorry, I'm not an expert in docker.  If I just build it then try to run the test.py script I still get the egInitialize() failed error

**Comment by NewtOliver** [comment]
您好，我也遇到了egInitialize() failed的错误，按照上述的办法并未解决，请问有什么好方法吗？
![image](https://user-images.githubusercontent.com/45253712/158053545-3bd89f02-83e5-42f0-8f4f-583387c5c73a.png)

我的Linux环境：
cudnn：8.6
cuda：11.3
python：3.7
pytorch：1.9.0

**Comment by liiffz** [comment]
I also encounter this problem when I run the code on our lab server. And that because the server missing some Nvidia drivers. Try to install the missing packages or just reinstall the whole driver.
You can see  [https://github.com/NVlabs/nvdiffrast/issues/51#issuecomment-954275825](url)[https://github.com/NVlabs/nvdiffrast/issues/56#issuecomment-983690874](url)[https://github.com/NVlabs/nvdiffrast/issues/24#issuecomment-824702760](url)

**Comment by YunjieYu** [comment]
@YuDeng hello, I also encounter `[F glutil.cpp:338] eglInitialize() failed` when running the inference code. My system environment is nvidia driver 450.80.02 and cuda 11.0. I already have a basic pytorch environment so only install OpenGL related libraries in my system environment (**not docker environment**) as suggested above. Specifically, I did the following steps:

1. I organize the contents of the dockerfile (provided by @yuzhou164) into an environment.sh:

```
apt-get update && apt-get install -y --no-install-recommends \
    pkg-config \
    libglvnd0 \
    libgl1 \
    libglx0 \
    libegl1 \
    libgles2 \
    libglvnd-dev \
    libgl1-mesa-dev \
    libegl1-mesa-dev \
    libgles2-mesa-dev \
    cmake \
    curl \
    libsm6 \
    libxext6 \
    libxrender-dev

# export PYTHONDONTWRITEBYTECODE=1
export PYTHONUNBUFFERED=1

# for GLEW
export LD_LIBRARY_PATH=/usr/lib:$LD_LIBRARY_PATH

# nvidia-container-runtime
export NVIDIA_VISIBLE_DEVICES=all
export NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics

# Default pyopengl to EGL for good headless rendering support
export PYOPENGL_PLATFORM=egl

cp docker/10_nvidia.json /usr/share/glvnd/egl_vendor.d/10_nvidia.json

pip install --upgrade pip
pip install ninja imageio imageio-ffmpeg
```

2. Run this environment.sh:
```
sudo bash environment.sh
```
3. Re-install nvdiffrast:
```
cd nvdiffrast    # ./Deep3DFaceRecon_pytorch/nvdiffrast
pip install .
```

I want to know if it is really caused by the nvidia driver version or some other problems.
Looking forward to your reply.

**Comment by Rodger-Huang** [comment]
According to https://github.com/NVlabs/nvdiffrast/issues/56#issuecomment-985228197, I successfully resolve this problem by reinstalling the NVIDIA driver without *-no-opengl-files*.

**Comment by ChenVoid** [comment]
> According to [NVlabs/nvdiffrast#56 (comment)](https://github.com/NVlabs/nvdiffrast/issues/56#issuecomment-985228197), I successfully resolve this problem by reinstalling the NVIDIA driver without _-no-opengl-files_.

May i ask how to reinstall the NVIDIA driver without -no-opengl-files? Could u provide more details? 
Looking forward to your assistant!

**Comment by ChenVoid** [comment]
> > > According to [NVlabs/nvdiffrast#56 (comment)](https://github.com/NVlabs/nvdiffrast/issues/56#issuecomment-985228197), I successfully resolve this problem by reinstalling the NVIDIA driver without _-no-opengl-files_.
> > 
> > 
> > May i ask how to reinstall the NVIDIA driver without -no-opengl-files? Could u provide more details? Looking forward to your assistance!
> 
> Hi, I downloaded the corresponding Nvidia Driver from https://www.nvidia.cn/Download/index.aspx?lang=cn and installed it without -no-opengl-files in my device.

Thank u ^^

**Comment by ChenVoid** [comment]
> > > > According to [NVlabs/nvdiffrast#56 (comment)](https://github.com/NVlabs/nvdiffrast/issues/56#issuecomment-985228197), I successfully resolve this problem by reinstalling the NVIDIA driver without _-no-opengl-files_.
> > > 
> > > 
> > > May i ask how to reinstall the NVIDIA driver without -no-opengl-files? Could u provide more details? Looking forward to your assistance!
> > 
> > 
> > Hi, I downloaded the corresponding Nvidia Driver from https://www.nvidia.cn/Download/index.aspx?lang=cn and installed it without -no-opengl-files in my device.
> 
> Thank u. But im using a gpu server. It seems to be difficult to change the default configuration.

**Comment by ChenVoid** [comment]
> > > According to [NVlabs/nvdiffrast#56 (comment)](https://github.com/NVlabs/nvdiffrast/issues/56#issuecomment-985228197), I successfully resolve this problem by reinstalling the NVIDIA driver without _-no-opengl-files_.
> > 
> > 
> > May i ask how to reinstall the NVIDIA driver without -no-opengl-files? Could u provide more details? Looking forward to your assistance!
> 
> Hi, I downloaded the corresponding Nvidia Driver from https://www.nvidia.cn/Download/index.aspx?lang=cn and installed it without -no-opengl-files in my device.

Very glad to receive your sincere reply.
EXM, i'm a newcomer on it. Could u explain more about how to "installed it without -no-opengl-files in my device."? Is there some tutorial for reinstalling Nvidia about it?
Thx.

**Comment by Rodger-Huang** [comment]
This blog (https://blog.csdn.net/weixin_43925119/article/details/109808670) may help you. When installing the Nvidia Driver, I changed the command "sudo ./NVIDIA-Linux-x86_64-430.14.run -no-x-check -no-nouveau-check -no-opengl-files" to "sudo ./NVIDIA-Linux-x86_64-430.14.run".

**Comment by ChenVoid** [comment]
@Rodger-Huang, thanks for your reply. 
By the way, do i need to re-install CUDA, Anaconda or PyTorch after reinstalling the Nvidia driver?

**Comment by SunYangtian** [comment]
> @YuDeng hello, I also encounter `[F glutil.cpp:338] eglInitialize() failed` when running the inference code. My system environment is nvidia driver 450.80.02 and cuda 11.0. I already have a basic pytorch environment so only install OpenGL related libraries in my system environment (**not docker environment**) as suggested above. Specifically, I did the following steps:
> 
> 1. I organize the contents of the dockerfile (provided by @yuzhou164) into an environment.sh:
> 
> ```
> apt-get update && apt-get install -y --no-install-recommends \
>     pkg-config \
>     libglvnd0 \
>     libgl1 \
>     libglx0 \
>     libegl1 \
>     libgles2 \
>     libglvnd-dev \
>     libgl1-mesa-dev \
>     libegl1-mesa-dev \
>     libgles2-mesa-dev \
>     cmake \
>     curl \
>     libsm6 \
>     libxext6 \
>     libxrender-dev
> 
> # export PYTHONDONTWRITEBYTECODE=1
> export PYTHONUNBUFFERED=1
> 
> # for GLEW
> export LD_LIBRARY_PATH=/usr/lib:$LD_LIBRARY_PATH
> 
> # nvidia-container-runtime
> export NVIDIA_VISIBLE_DEVICES=all
> export NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
> 
> # Default pyopengl to EGL for good headless rendering support
> export PYOPENGL_PLATFORM=egl
> 
> cp docker/10_nvidia.json /usr/share/glvnd/egl_vendor.d/10_nvidia.json
> 
> pip install --upgrade pip
> pip install ninja imageio imageio-ffmpeg
> ```
> 
> 2. Run this environment.sh:
> 
> ```
> sudo bash environment.sh
> ```
> 
> 3. Re-install nvdiffrast:
> 
> ```
> cd nvdiffrast    # ./Deep3DFaceRecon_pytorch/nvdiffrast
> pip install .
> ```
> 
> I want to know if it is really caused by the nvidia driver version or some other problems. Looking forward to your reply.

The same problem came across to me.  It seems that the  use of a low version OpenGL  (specifically, Mesa instead of Nvidia) caused this error.

**Comment by duongminhhieu16** [comment]
@SunYangtian Could you explain more? The previous solution is not working because I don't have permission to reinstall the nvidia driver.

**Comment by sicxu** [comment]
Following #108, we have updated the code and README to support CUDA context. For someone having trouble installing OpenGL, you may try to add "--use_opengl False" to the script to switch to using CUDA context.

**Comment by Walterkd** [comment]
# Solution
Replace all `dr.RasterizeGLContext` to `dr.RasterizeCudaContext`

**Comment by Blue-FishER** [comment]
> # Solution
> Replace all `dr.RasterizeGLContext` to `dr.RasterizeCudaContext`

I have tried different images using docker, and all failed with the same error. But this works for me. And these codes are located in util/nvdiffrast.py Line 62. I do like this:
`if self.ctx is None:
            self.ctx = dr.RasterizeCudaContext(device=device)
            ctx_str = "cuda"
            # if self.use_opengl:
            #     self.ctx = dr.RasterizeGLContext(device=device)
            #     ctx_str = "opengl"
            # else:
            #     self.ctx = dr.RasterizeCudaContext(device=device)
            #     ctx_str = "cuda"
            # print("create %s ctx on device cuda:%d"%(ctx_str, device.index))`

**Comment by lydonchandra** [comment]
> # Solution
> Replace all `dr.RasterizeGLContext` to `dr.RasterizeCudaContext`

Thank you, confirmed this worked for me too.

**Comment by Pamimi** [comment]
> [F glutil.cpp:338] eglInitialize() failed
I solved this by 
```sudo apt-get install libnvidia-gl-xxx-server```
xxx is your nvidia driver version, you can find that by `nvidia-smi`
