### ISSUE TITLE
请问一下，我现在想把原图和通过BFM所得到的顶点属性（texture和color）转换到UV空间，这部分要如何实现呢？有什么参考资料吗？

### ISSUE THREAD

**Issue by 1151537695** [sicxu/Deep3DFaceRecon_pytorch#20]

**Comment by YuDeng** [comment]
hi, 关于转换到uv空间，可参考https://github.com/anilbas/3DMMasSTN

**Comment by 1151537695** [comment]
非常感谢！！！

**Comment by mengxuyiGit** [comment]
hi 请问您成功实现了吗？https://github.com/anilbas/3DMMasSTN貌似也没有给出具体的操作（比如如何转到tutted embedding）
