### ISSUE TITLE
关于NoW challenge？

### ISSUE THREAD

**Issue by zyqlalala** [sicxu/Deep3DFaceRecon_pytorch#21]
想问一下是如何得到NoW challenge里人脸图片的5 lmk，是人脸图片直接用"How far are we from solving the 2D & 3D Face Alignment problem? (and a dataset of 230,000 3D facial landmarks"的3D lmk 检测还是用了NoW里提供的bbox直接裁剪成256x256?参加挑战的模型是公开的epoch_20.pth吗？生成的obj文件里顶点的精度是np.float32吗？

**Comment by YuDeng** [comment]
Hi, 关于5点landmark,我们使用了"How far"得到，之后根据5点剪裁成我们网络需要的输入形式。
repo中提供的epoch_20.pth就是NoW challenge里用到的model。
obj文件默认精度是float32,但是这个精度对最后结果的影响其实微乎其微。

**Comment by zyqlalala** [comment]
> Hi, 关于5点landmark,我们使用了"How far"得到，之后根据5点剪裁成我们网络需要的输入形式。
> repo中提供的epoch_20.pth就是NoW challenge里用到的model。
> obj文件默认精度是float32,但是这个精度对最后结果的影响其实微乎其微。

那想问一下比如现在有一张NoW的test集提供的image_A， 通过模型预测出了3DMM参数 coeff_A， 如果要生成参加NoW挑战的obj格式，是否只需要保留coeff_A中shape coeff对mesh的影响，其余如exp则保持中性，angle coeff和trans coeff对其obj也不产生影响？

**Comment by YuDeng** [comment]
angle 和 trans对结果不会有影响，因为NoW在测试的时候会对结果做三维对齐。shape和exp应该都需要保留，exp不要变成中性的。具体可参考NoW网站的说明。

**Comment by zyqlalala** [comment]
> angle 和 trans对结果不会有影响，因为NoW在测试的时候会对结果做三维对齐。shape和exp应该都需要保留，exp不要变成中性的。具体可参考NoW网站的说明。

还想问一下对训练图片预处理获得mask以及68个lm，其原理以及用到的方法，tf版本与pytorch版本是否一致？

**Comment by YuDeng** [comment]
是一致的。唯一区别是pytorch版本的landmark detector要比tf版本的准确一些。

**Comment by o0Helloworld0o** [comment]
> angle 和 trans对结果不会有影响，因为NoW在测试的时候会对结果做三维对齐。shape和exp应该都需要保留，exp不要变成中性的。具体可参考NoW网站的说明。

NoW challenge网站上的原文：The challenge for all categories is to reconstruct a neutral 3D face given a single monocular image. Note that facial expressions are present in several images, which requires methods to disentangle identity and expression to evaluate the quality of the predicted identity.

关键词：reconstruct a neutral 3D face；evaluate the quality of the predicted identity

所以我认为对于给定的测试图像预测出shape系数和exp系数，需要把exp系数置0才能生成预测的3Dmesh（方案1），这样才是符合NoW challenge的用意的；当然shape和exp都保留也可以去提交一个submission（方案2）
如果方案1比方案2得分更高是合理的，如果方案1比不过方案2，那么说明NoW这个benchmark不太靠谱，不如去最新的FaceScape benchmark上做评测

**Comment by yisongsong** [comment]
> > angle 和 trans对结果不会有影响，因为NoW在测试的时候会对结果做三维对齐。shape和exp应该都需要保留，exp不要变成中性的。具体可参考NoW网站的说明。
> 
> NoW challenge网站上的原文：The challenge for all categories is to reconstruct a neutral 3D face given a single monocular image. Note that facial expressions are present in several images, which requires methods to disentangle identity and expression to evaluate the quality of the predicted identity.
> 
> 关键词：reconstruct a neutral 3D face；evaluate the quality of the predicted identity
> 
> 所以我认为对于给定的测试图像预测出shape系数和exp系数，需要把exp系数置0才能生成预测的3Dmesh（方案1），这样才是符合NoW challenge的用意的；当然shape和exp都保留也可以去提交一个submission（方案2） 如果方案1比方案2得分更高是合理的，如果方案1比不过方案2，那么说明NoW这个benchmark不太靠谱，不如去最新的FaceScape benchmark上做评测

DECA 上测试，方案1 比 方案2 好，不过差别很小

**Comment by wengjincheng** [comment]
@YuDeng @o0Helloworld0o 项目里生成的obj mesh 无法使用NoW evaluation的mesh去展示，想问下这是需要更换mesh export的方法吗？
