### ISSUE TITLE
Include neck and ears in generated model

### ISSUE THREAD

**Issue by UserCnX** [sicxu/Deep3DFaceRecon_pytorch#22]
Hi there,

Can you please tell me how I can include neck and ears in the generated model?  I am assuming that I need to made some changes in the transferBFM09 method of util/load_mats.py, but any changes to index_exp (lines 61-62) is causing runtime errors in a number of other files.

Any help would be much appreciated

**Comment by YuDeng** [comment]
Hi,

To genertate neck and ears, you need two modifications:

First, you have to comment out this line: https://github.com/sicxu/Deep3DFaceRecon_pytorch/blob/73d491102af6731bded9ae6b3cc7466c3b2e9e48/util/load_mats.py#L67
This will ensure that you also include vertices in neck and ears region.

Second, you need to re-compute the triangle information from the original_BFM. This is a bit tricky. You have to make sure that you only include the triangles that contain the vertices you selected. And you also need to re-compute the vertices index in the triangle.

**Comment by UserCnX** [comment]
Hi there,

Many thanks for getting back to me, I will try your suggestion,

Kind Regards,

John

**Comment by LY-Donkey-Burger** [comment]
> 



> 你好呀，
> 
> 非常感谢您回复我，我会尝试您的建议，
> 
> 亲爱的问候，
> 
> 约翰



> 

Hi，did you succeed?
