### ISSUE TITLE
Multi images inferencing

### ISSUE THREAD

**Issue by icedpanda** [sicxu/Deep3DFaceRecon_pytorch#27]
Hi @YuDeng , Thank you for sharing your great work.

How can I do model inferencing for the multi-image case as there is no C-Net available yet? My dataset has three images for each person and was taken from frontal and side.

You mentioned we could use the average shape for the multi-image case in #17 . I'm new to this area. Could you please expand on this?

If you could provide some example code would be much appreciated.

Thanks

**Comment by YuDeng** [comment]
Hi, you can take the average of the 'id' coefficients predicted by different images here: https://github.com/sicxu/Deep3DFaceRecon_pytorch/blob/73d491102af6731bded9ae6b3cc7466c3b2e9e48/models/bfm.py#L283, and set the 'exp' coef to zero. Then you just need to send the modified coef_dict to the reconstruction pipeline and it will return you an average face shape.

**Comment by icedpanda** [comment]
Correct me if I am wrong. I suspect the model would also need face landmarks from those additional images. If so, this may not apply to my case since other images were captured from the side and do not have landmarks like eyes, nose, etc. 

Thanks

**Comment by pyxploiter** [comment]
> Correct me if I am wrong. I suspect the model would also need face landmarks from those additional images. If so, this may not apply to my case since other images were captured from the side and do not have landmarks like eyes, nose, etc.
> 
> Thanks

Hi @icedpanda,  were you able to run this for multi images?

**Comment by icedpanda** [comment]
@pyxploiter Haven't had a chance to run multi images yet, but a single image looks fine

**Comment by WildPant** [comment]
@icedpanda 

> @pyxploiter还没有机会运行多张图片，但单张图片看起来不错
Have you found a job that fits your dataset?
