### ISSUE TITLE
RuntimeError: Ninja is required to load C++ extensions

### ISSUE THREAD

**Issue by PandaChen-pro** [sicxu/Deep3DFaceRecon_pytorch#35]
I don't know how to solve the problem,please help me!!!

**Comment by UestcJay** [comment]
hi I also meet this problem, can you help me?

**Comment by PandaChen-pro** [comment]
Sorry，I havn't solved the problem yet.

**Comment by sdulyq** [comment]
Install Ninja will help. I solved it.

**Comment by daqiudi** [comment]
> Install Ninja will help. I solved it.

你好，请问你是怎么解决这个问题的，是用pip安装Ninja 吗，具体是什么版本呢
