### ISSUE TITLE
How to get 3D keypoints in order to evaluate in NoW challenge?

### ISSUE THREAD

**Issue by minoslee** [sicxu/Deep3DFaceRecon_pytorch#37]
Thanks for your greate work! I'm a recruit for 3d reconstruction , and I want to evaluate my model in NoW challenge. I follow the guide from [https://github.com/soubhiksanyal/now_evaluation](https://github.com/soubhiksanyal/now_evaluation) 
```
python check_predictions.py <predicted_mesh_path> <predicted_mesh_landmark_path> <gt_scan_path> <gt_lmk_path> 
```
There is a little doubt about the <predicted_mesh_landmark_path>. It looks like the file containing 3D coordinates of 7 key points. Can you give me some advice or guidance on obtaining the 3D coordinates of key points？ Thanks again!

**Comment by YuDeng** [comment]
Hi, we first select 7 vertices on the template mesh (mean shape) as keypoints indicated by NoW, Then we automatically calculate the 3D coordinates of 7 keypoints for each subjects from their reconstructed meshes.

**Comment by DoubleYanLee** [comment]
Hi! thank you for releasing the code for your amazing research!  When I evaluate my model (pre_model also be evaluated) in NoW challenge,  I also follow the guide from https://github.com/soubhiksanyal/now_evaluation.

`python check_predictions.py <predicted_mesh_path>`
this code exports the input mesh to `predicted_mesh_export.obj` . when I open the mesh in MeshLab, I find it not a face shape. it just like that:

![4B078A5D8EA5DF7B00F8C7DB239B3BEE](https://user-images.githubusercontent.com/25344948/141043719-6ce00343-4228-417b-9d0d-d52d752dce55.png)

I find the page said: "The used mesh loader is unable to load OBJ files with vertex colors appended to the vertices. I.e. if the OBJ contains lines of the following format v vx vy vz cr cg cb\n, export the meshes without vertex colors."

I wonder if the reason is the obj file outputed by test obtained the vertex colors. 

Again, thank you for your attention!

**Comment by minoslee** [comment]
> Hi! thank you for releasing the code for your amazing research! When I evaluate my model (pre_model also be evaluated) in NoW challenge, I also follow the guide from https://github.com/soubhiksanyal/now_evaluation.
> 
> `python check_predictions.py <predicted_mesh_path>` this code exports the input mesh to `predicted_mesh_export.obj` . when I open the mesh in MeshLab, I find it not a face shape. it just like that:
> 
> ![4B078A5D8EA5DF7B00F8C7DB239B3BEE](https://user-images.githubusercontent.com/25344948/141043719-6ce00343-4228-417b-9d0d-d52d752dce55.png)
> 
> I find the page said: "The used mesh loader is unable to load OBJ files with vertex colors appended to the vertices. I.e. if the OBJ contains lines of the following format v vx vy vz cr cg cb\n, export the meshes without vertex colors."
> 
> I wonder if the reason is the obj file outputed by test obtained the vertex colors.
> 
> Again, thank you for your attention!



> Hi! thank you for releasing the code for your amazing research! When I evaluate my model (pre_model also be evaluated) in NoW challenge, I also follow the guide from https://github.com/soubhiksanyal/now_evaluation.
> 
> `python check_predictions.py <predicted_mesh_path>` this code exports the input mesh to `predicted_mesh_export.obj` . when I open the mesh in MeshLab, I find it not a face shape. it just like that:
> 
> ![4B078A5D8EA5DF7B00F8C7DB239B3BEE](https://user-images.githubusercontent.com/25344948/141043719-6ce00343-4228-417b-9d0d-d52d752dce55.png)
> 
> I find the page said: "The used mesh loader is unable to load OBJ files with vertex colors appended to the vertices. I.e. if the OBJ contains lines of the following format v vx vy vz cr cg cb\n, export the meshes without vertex colors."
> 
> I wonder if the reason is the obj file outputed by test obtained the vertex colors.
> 
> Again, thank you for your attention!

Hi~ I meet the same issue in the first time with default test.py. On the 66 line in test.py , it save the .obj file using save_mesh()function, and you can edit the function in 215 line in facerecon_model.py, just remove the 
```
vertex_colors=np.clip(255. * recon_color, 0, 255).astype(np.uint8)
```
In this way, I can get the correct .obj file after executing check_predictions.py.

By the way, did you get 3d coordinates  of 7 key points? I'm still a little confused about that.. Thanks for your attention.

**Comment by DoubleYanLee** [comment]
> > Hi! thank you for releasing the code for your amazing research! When I evaluate my model (pre_model also be evaluated) in NoW challenge, I also follow the guide from https://github.com/soubhiksanyal/now_evaluation.
> > `python check_predictions.py <predicted_mesh_path>` this code exports the input mesh to `predicted_mesh_export.obj` . when I open the mesh in MeshLab, I find it not a face shape. it just like that:
> > ![4B078A5D8EA5DF7B00F8C7DB239B3BEE](https://user-images.githubusercontent.com/25344948/141043719-6ce00343-4228-417b-9d0d-d52d752dce55.png)
> > I find the page said: "The used mesh loader is unable to load OBJ files with vertex colors appended to the vertices. I.e. if the OBJ contains lines of the following format v vx vy vz cr cg cb\n, export the meshes without vertex colors."
> > I wonder if the reason is the obj file outputed by test obtained the vertex colors.
> > Again, thank you for your attention!
> 
> Hi~ I meet the same issue in the first time with default test.py. On the 66 line in test.py , it save the .obj file using save_mesh()function, and you can edit the function in 215 line in facerecon_model.py, just remove the
> 
> ```
> vertex_colors=np.clip(255. * recon_color, 0, 255).astype(np.uint8)
> ```
> 
> In this way, I can get the correct .obj file after executing check_predictions.py.
> 
> By the way, did you get 3d coordinates of 7 key points? I'm still a little confused about that.. Thanks for your attention.

sorry, I just saw your answer. This solved my problem, Thank you! 

For the question about getting 3d coordinates of 7 key points, I guess we need to get 3d coordinates of 7 key points in the BFM model(Maybe in the function save_mesh of facerecon_model.py) In 68 landmarks, We could use the landmarks with indices [36,39,42,45,33,48,55] , But I don't know if it works on the problem. Thanks for your attention.

**Comment by AyushP123** [comment]
Hi @YuDeng,

For computing, the 7 3D locations for the NoW benchmark is the following procedure correct?
1. Use the 7 landmark points from the `similarity_Lm3D_all.mat` and find the index of the nearest vertices for those in the mean shape.
2. Use the same indices in the final shape to get the 3D landmark points

**Comment by wengjincheng** [comment]
> 

I found that just selecting 7 key landmarks by the array that you mentioned, the result of distance calculated by now_evaluate  was very large.

![image](https://user-images.githubusercontent.com/20600119/209427005-71716bac-daea-4579-b058-6bb84738881c.png)

**Comment by wengjincheng** [comment]
> Hi @YuDeng,
> 
> For computing, the 7 3D locations for the NoW benchmark is the following procedure correct?
> 
> 1. Use the 7 landmark points from the `similarity_Lm3D_all.mat` and find the index of the nearest vertices for those in the mean shape.
> 2. Use the same indices in the final shape to get the 3D landmark points

Hi have you found the correct indices of these 7 landmarks?

**Comment by WangXuan2401** [comment]
> > Hi! thank you for releasing the code for your amazing research! When I evaluate my model (pre_model also be evaluated) in NoW challenge, I also follow the guide from https://github.com/soubhiksanyal/now_evaluation.
> > `python check_predictions.py <predicted_mesh_path>` this code exports the input mesh to `predicted_mesh_export.obj` . when I open the mesh in MeshLab, I find it not a face shape. it just like that:
> > ![4B078A5D8EA5DF7B00F8C7DB239B3BEE](https://user-images.githubusercontent.com/25344948/141043719-6ce00343-4228-417b-9d0d-d52d752dce55.png)
> > I find the page said: "The used mesh loader is unable to load OBJ files with vertex colors appended to the vertices. I.e. if the OBJ contains lines of the following format v vx vy vz cr cg cb\n, export the meshes without vertex colors."
> > I wonder if the reason is the obj file outputed by test obtained the vertex colors.
> > Again, thank you for your attention!
> 
> Hi~ I meet the same issue in the first time with default test.py. On the 66 line in test.py , it save the .obj file using save_mesh()function, and you can edit the function in 215 line in facerecon_model.py, just remove the
> 
> ```
> vertex_colors=np.clip(255. * recon_color, 0, 255).astype(np.uint8)
> ```
> 
> In this way, I can get the correct .obj file after executing check_predictions.py.
> 
> By the way, did you get 3d coordinates of 7 key points? I'm still a little confused about that.. Thanks for your attention.

thanks a lot for your contribution
