### ISSUE TITLE
How to set focal, z_near and z_far?

### ISSUE THREAD

**Issue by xjcvip007** [sicxu/Deep3DFaceRecon_pytorch#43]
Thank you for your amazing job! Two question: (1) If I want to modify size of input image(eg. 224 -> 112), How can I set focal, z_near and z_far?  (2) why choose focal == 1015 for image size 224? Looking for your response~

**Comment by HarshWinterBytes** [comment]
Have you solved this problem? I also want to modify these parameters now.

**Comment by sicxu** [comment]
It‘s been a little bit tricky. You can change the focal and the center with the scale by the projection matrix. For example, you want to change the input image size from 224->224/2, you need to scale the focal from 1015 to 1015/2 and the center from 112 to 112/2.
1015 is just an empirical number, you may change it by you purpose.
