### ISSUE TITLE
setup on CPU only machines

### ISSUE THREAD

**Issue by Koushik0901** [sicxu/Deep3DFaceRecon_pytorch#44]
Hi there, This is an awesome repo and I love it. It seems that nvdiffrast is tightly integrated with cuda and I couldn't find a way to properly make it work on a CPU-only machine. So It would be nice if you could guide me on setting this up on a CPU-only machine.

**Comment by CherprangA** [comment]
The TensorFlow version of this repo can work on a CPU-only machine. You just have to install tensorflow==1.12.0 instead of tensorflow-gpu==1.12.0 in their instructions.

**Comment by Koushik0901** [comment]
Thanks!
