### ISSUE TITLE
How to understand the parameter "camera_d"

### ISSUE THREAD

**Issue by HarshWinterBytes** [sicxu/Deep3DFaceRecon_pytorch#46]
Thank you for your excellent job! 
In your work, the resolution of all input images will be processed as 224 * 224. Now I want to change the resolution to 512 * 512, and then I find that if I want to change the resolution, changing the five rendering parameters(focal, center, camera_d, z_near, z_far) is necessary. But I don't know how to understand the parameter "camera_d" now.

**Comment by sicxu** [comment]
You may take this camera_d as a depth prior that we assume the distance between face and camera is 1m.

**Comment by chinaandylee** [comment]
from 224*224 to 512*512, how to adjust focal, center, camera_d, z_near, z_far？@sicxu @HarshWinterBytes

**Comment by yoobin-jeong** [comment]
@sicxu does the distance between face and camera mean distance from camera center to the closest point to the face (such as nose tip)?
