### ISSUE TITLE
Can't download 01_MorphableModel.mat

### ISSUE THREAD

**Issue by lucydjo** [sicxu/Deep3DFaceRecon_pytorch#5]
Hello, 

impossible to download the file via https://faces.dmi.unibas.ch/bfm/main.php?nav=1-2&id=downloads because I don't receive the email.

Too bad to waste all this work for a simple email

**Comment by loretoparisi** [comment]
@lucydjo is [this](https://github.com/sicxu/Deep3DFaceRecon_pytorch/issues/39) issue related to this additional download?

**Comment by lucydjo** [comment]
> @lucydjo is [this](https://github.com/sicxu/Deep3DFaceRecon_pytorch/issues/39) issue related to this additional download?

I didn't receive the download email, I had to wait a long time. 😕
