### ISSUE TITLE
Blue eyes appear when I adjust the render resolution

### ISSUE THREAD

**Issue by DoubleYanLee** [sicxu/Deep3DFaceRecon_pytorch#51]
I have upsampled the image in order to reduce aliasing. The resulting image became much smoother except for the eye part, where there is obvious noise:

![IMG_0053](https://user-images.githubusercontent.com/25344948/146669648-ca46837c-42ad-47f5-a86e-239d56c4088b.png)
 
Here's the code I've used to produce the middle image:

```python
high_resolution_rast, _ = dr.rasterize(self.glctx, vertex_ndc.contiguous(), tri, resolution=[1120, 1120], ranges=ranges)
high_resolution_image, _ = dr.interpolate(feat, high_resolution_rast, tri)

sum_mask_mat = self.sum_mask_mat.to(device)
sum_image_mat = self.sum_image_mat.to(device)

mask_avg = high_resolution_image.sum(3)[:, :, :, None]
mask_avg[mask_avg > 0] = 1.0
mask_avg = mask_avg.permute(0, 3, 1, 2)

mask_avg = torch.nn.functional.conv2d(mask_avg, sum_mask_mat, stride=5, padding=2)
mask_avg[mask_avg == 0.0] = 1.0

conv_image = torch.nn.functional.conv2d(high_resolution_image.permute(0, 3, 1, 2), sum_image_mat, stride=5, padding=2, groups=3)
conv_image = conv_image.div(mask_avg)
```

Is there something wrong with my code?

I will greatly appreciate your help.

**Comment by YuDeng** [comment]
Hi, this problem seems to be caused by out of range issue. You can clip the color value within 0-255 to avoid it.

**Comment by DoubleYanLee** [comment]
Thanks! It solved my problem!
