### ISSUE TITLE
The verts of the saved mesh seems been shuffled

### ISSUE THREAD

**Issue by qiuyuda** [sicxu/Deep3DFaceRecon_pytorch#56]
Hi. Thanks for the sharing.
When running the test code, I found the verts of the saved mesh seem been shuffled. (in save_mesh function)

Maybe it's caused by Trimesh libs. I think there should be a flag to fix the orders in the Trimesh function? or just replace the Trimesh saving process with other codes.

**Comment by sicxu** [comment]
Thanks for your suggest, I have not checked it yet, but I believe it's unessential. You may create a PR to fix this "issue" if you want.
