### ISSUE TITLE
请问报错说需要opegl4.4以上怎么解决

### ISSUE THREAD

**Issue by madgnot** [sicxu/Deep3DFaceRecon_pytorch#57]

**Comment by sdulyq** [comment]
请问你解决了吗

**Comment by pcgreat** [comment]
I got the same problem, and I solved it by
installing nvdiffrast>=0.3.0, and then replace dr.RasterizeGLContext() with dr.RasterizeCudaContext() in util/nvdiffrast.py, so that it uses CUDA instead of OpenGL

**Comment by sicxu** [comment]
> I got the same problem, and I solved it by installing nvdiffrast>=0.3.0, and then replace dr.RasterizeGLContext() with dr.RasterizeCudaContext() in util/nvdiffrast.py, so that it uses CUDA instead of OpenGL

Yeah, that may solve this problem, I have updated the code to support this switch more easily. By adding "--use_opengl False" to the script, you may use the CUDA context instead of Opengl context.
