### ISSUE TITLE
License for pytorch implementation of Deep3DFaceReconstruction

### ISSUE THREAD

**Issue by Sibylle-Van-Hove** [sicxu/Deep3DFaceRecon_pytorch#58]
Hi, 

Does this pytorch implementation of Depp3DFaceReconstuction have the same MIT license as the original tensorflow implementation?
https://github.com/microsoft/Deep3DFaceReconstruction

Thanks

**Comment by sicxu** [comment]
Yes, thanks for your reminder, the MIT license has been added.
