### ISSUE TITLE
mtcnn did not generate the required txt file

### ISSUE THREAD

**Issue by AKclown** [sicxu/Deep3DFaceRecon_pytorch#6]
Hello, I am using mtcnn and there is no corresponding txt file, but only a picture of the detection point is generated for me. Is my operation wrong?

I run mtcnn output results
![QQ图片20210725095045](https://user-images.githubusercontent.com/33648653/126885090-fd821ea0-da9c-479a-8f8f-269750c4cd01.jpg)

According to the documentation, how should I map the monitoring points to a txt file?  thanks
![image](https://user-images.githubusercontent.com/33648653/126885021-90ffc23a-4789-4089-ba88-ba760aec6f2c.png)

**Comment by AKclown** [comment]
Sorry I didn’t look carefully, there is this information in the console

**Comment by CGMikeG** [comment]
Sorry I was looking for this as well but so far no luck. Can you point me to the right direction on how to get txt file.
