### ISSUE TITLE
How can I use the the novel multi-image face reconstruction methods mentioned in the article 

### ISSUE THREAD

**Issue by ghost** [sicxu/Deep3DFaceRecon_pytorch#64]
I have try: python test.py --name=<model_name> --epoch=20 --img_folder=<folder_to_test_images>
that ok. but this is single image.
in the paper at “6.2. Results on Multi-Image Reconstruction”. how can I use this methods in the code.

**Comment by FernandoConti** [comment]
I just wanted to ask the same thing, would be great to test it.

**Comment by sicxu** [comment]
This repo is only for single-view reconstruction.

**Comment by cnnAndBn** [comment]
@sicxu will you plan to release multi image same person solution ?
