### ISSUE TITLE
About 3dmm model

### ISSUE THREAD

**Issue by ozhyo** [sicxu/Deep3DFaceRecon_pytorch#71]
I found a conflict in models/bfm.py. It's when we load point_buf and face_buf in line 53 and line 55. I check the shape of face_buf, which is (70789, 3), and this indicates total number of faces is 70789. But when I check the point_buf, I found the max value is 70789, and the min value is 0. The point_buf indicates there are 70790 faces in total, which conflicts with the face_buf. The conflict may cause an "index out of range" error. I wonder why there is a conflict and how to solve it.

**Comment by sicxu** [comment]
Yes, when we use the point_buf to index tensors, we just pad some invalid values to avoid the conflict.
For example:
https://github.com/sicxu/Deep3DFaceRecon_pytorch/blob/6ba3d22f84bf508f0dde002da8fff277196fef21/models/bfm.py#L133-L136

**Comment by ozhyo** [comment]
Thanks for your reply. Now I know how to deal with it. But it still confuses me why there is difference between point_buf and face_buf.

**Comment by sicxu** [comment]
Padding the surrounding faces of each point to the same number is a easy trick used for parallel computation. 
To make this point_buf totally make sense, you can padding a invalid vector to the verts to get total n+1 verts. Then you can add an extra face i.e. (n+1, n+1, n+1) to face_buf to get total m+1 face.

**Comment by ozhyo** [comment]
Thanks a lot ! Now I think I understand it. And maybe I should close this issue.
