### ISSUE TITLE
How to adjust focal, center, camera_d, z_near, z_far, when changing input image size from 224*224 to 512*512 

### ISSUE THREAD

**Issue by chinaandylee** [sicxu/Deep3DFaceRecon_pytorch#84]
from 224*224 to 512*512, how to adjust focal, center, camera_d, z_near, z_far?Thanks!

**Comment by chinaandylee** [comment]
when I change 
parser.add_argument('--focal', type=float, default=1015.)  to parser.add_argument('--focal', type=float, default=1015.*512/224)
parser.add_argument('--center', type=float, default=112.) to parser.add_argument('--center', type=float, default=112.*512/224) 
I got the following results. what I am missing?
![image](https://user-images.githubusercontent.com/31954506/168708281-48c2682f-5ef5-444c-a479-727d3f6adaf6.png)

**Comment by sicxu** [comment]
Our model is trained under 224x224 resolution, if your directly change the input resolution, it should not work. You can either retrain the model or process the input by the right way and then re-project the resulting mesh to the original resolution. #49
