### ISSUE TITLE
how to get the *.txt file about facial landmarks?

### ISSUE THREAD

**Issue by sablea** [sicxu/Deep3DFaceRecon_pytorch#85]
In Readme.md,
"The *.jpg/*.png files are test images. **The *.txt files are detected 5 facial landmarks with a shape of 5x2**, and have the same name as the corresponding images. Check [./datasets/examples](https://github.com/sicxu/Deep3DFaceRecon_pytorch/blob/master/datasets/examples) for a reference."
I want to know how to get them.

**Comment by brurpo** [comment]
I use MTCNN to do it, like the docs suggested (you can also use dlib).
you can pip install it (make sure you also have opencv-python)
you will also need nvidia dlls to make use of gpu acceleration but its not required

This is how I did it, it works on jpgs only, but you can alter it
I made this for use in a video, so there is an if else there to reuse previous frames if the prediction is poor on current frame, just remove it to use on arbitrary images.
call it in a cmd line or batch to generate the txts

```
import os
import re
import math
os.add_dll_directory(os.getcwd())

import argparse
from mtcnn import MTCNN
import cv2

def find_between( s, first, last ):
    try:
        start = s.index( first ) + len( first )
        end = s.index( last, start )
        return s[start:end]
    except ValueError:
        return ""

def main(args):
    #img = cv2.cvtColor(cv2.imread("ivan.jpg"), cv2.COLOR_BGR2RGB)
    detector = MTCNN()


    directory = os.path.abspath(args.image_folder)
    totals = len(os.listdir(directory))
    j = 0
    for file in os.listdir(directory):
         filename = os.path.join(directory, file)
         if filename.endswith(".jpg"):
             img = cv2.cvtColor(cv2.imread(filename), cv2.COLOR_BGR2RGB)
             detect = detector.detect_faces(img)
             confidence = detect[0]['confidence']
             bbox =  detect[0]['box']
             #print(totals)
             if j < 1: print("Detection progress: " + str(round((j/totals)*100,2)) + "%")
             if float(confidence) > 0.95 or j < 1:
                 Leye = find_between(str(detect), '\'left_eye\': (', ')').replace(', ', '\t')
                 Reye = find_between(str(detect), '\'right_eye\': (', ')').replace(', ', '\t')
                 nose = find_between(str(detect), '\'nose\': (', ')').replace(', ', '\t')
                 Lmouth = find_between(str(detect), '\'mouth_left\': (', ')').replace(', ', '\t')
                 Rmouth = find_between(str(detect), '\'mouth_right\': (', ')').replace(', ', '\t')
                 centerX = (float(bbox[0])+(float(bbox[2])/2.0)) #center X
                 centerY = (float(bbox[1])+(float(bbox[3])/2.0)) #center Y
                 LeyeB = Leye
                 ReyeB = Reye
                 noseB = nose
                 LmouthB = Lmouth
                 RmouthB = Rmouth
                 centerXB = centerX
                 centerYB = centerY
             else:
                 print('low confidence')
                 Leye = LeyeB
                 Reye = ReyeB
                 nose = noseB
                 Lmouth = LmouthB
                 Rmouth = RmouthB
                 centerX = centerXB
                 centerY = centerYB
             #print(Leye + '\n' + Reye + '\n' + nose + '\n' + Lmouth + '\n' + Rmouth)
             f = open(os.path.join(directory, 'detections\\', file.replace('.jpg', '.txt')), "w")
             f.write(Leye + '\n' + Reye + '\n' + nose + '\n' + Lmouth + '\n' + Rmouth)
             f.close()
             f2 = open(os.path.join(directory, 'detections\\', file.replace('.jpg', '.center')), "w")
             f2.write(str(centerX) + '\n' + str(centerY))
             f2.close()
             j+=1
             print("Detection progress: " + str(round((j/totals)*100,2)) + "%")



             continue
             #break
         else:
             continue


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Detect Faces')
    parser.add_argument('-i', '--image_folder', type=str, default='configs/')


    args = parser.parse_args()
    main(args)

```

**Comment by LiUzHiAn** [comment]
I wrote script to extarct the facial landmarks using dlib, and the 68 points and 5 point are both supported:
```
"""
Ref: https://pyimagesearch.com/2017/04/03/facial-landmarks-dlib-opencv-python/
"""

from tqdm import tqdm
import os
import numpy as np
import argparse
import dlib
import cv2
from glob import glob

def rect_to_bb(rect):
	# take a bounding predicted by dlib and convert it
	# to the format (x, y, w, h) as we would normally do
	# with OpenCV
	x = rect.left()
	y = rect.top()
	w = rect.right() - x
	h = rect.bottom() - y
	# return a tuple of (x, y, w, h)
	return (x, y, w, h)


def lmk_to_np(shape, dtype="int32"):
	# initialize the list of (x, y)-coordinates
	coords = np.zeros((shape.num_parts, 2), dtype=dtype)
	# loop over the 68 facial landmarks and convert them to a 2-tuple of (x, y)-coordinates
	for i in range(0, shape.num_parts):
		coords[i] = (shape.part(i).x, shape.part(i).y)
	# return the list of (x, y)-coordinates
	return coords

# lmk-68p to lmk-5p
def extract_5p(lm, dtype="int32"):
    lm_idx = np.array([31, 37, 40, 43, 46, 49, 55]) - 1
    lm5p = np.stack([lm[lm_idx[0], :], np.mean(lm[lm_idx[[1, 2]], :], 0), np.mean(
        lm[lm_idx[[3, 4]], :], 0), lm[lm_idx[5], :], lm[lm_idx[6], :]], axis=0)
    lm5p = lm5p[[1, 2, 0, 3, 4], :].astype(dtype)
    
    return lm5p  # [left_eye, right_eye, nose, left_mouth, right_mouth]



def save_lmks_to_file(lmks, file):
    with open(file, "w") as f:
        for i in range(len(lmks)):
            f.write(str(lmks[i][0])+" "+str(lmks[i][0]))  # x,y coordiantes

            if i != len(lmks)-1:
                f.write("\n")
    

# +--------------------------------------------------------------------------     
#  Extract facial landmarks (68 points and 5 points are both supported).
#
#  Running example:
#
#       python lmk_dlib_detect.py -i <XXX.png or path_to_image_dir> \
#                                    -o <output_dir> \
#                                   [-p dlib_shape_predictor] \
#                                   [-v vis_dir] \
#                                   [-lmk5p vis_dir]
#                                   
# +--------------------------------------------------------------------------       

ap = argparse.ArgumentParser()
ap.add_argument("-p", "--shape-predictor", default="shape_predictor_68_face_landmarks.dat", help="path to facial landmark predictor")
ap.add_argument("-i", "--input", type=str, default= "./realign1500/", help="path to input image or input folders")
ap.add_argument("-o", "--output", type=str, default= "lmk", help="path to output directory for landmark saving")
ap.add_argument("-v", "--vis", type=str, default="", help="path to output directory for landmark visualization")
ap.add_argument("--lmk5p", action="store_true", default=True, help="convert lmk68 to lmk5")
args = vars(ap.parse_args())


detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor(args["shape_predictor"])

if os.path.isdir(args["input"]):
    imgs = glob(os.path.join(args["input"], "*.*g"))
else:
    imgs = [args["input"]]

os.makedirs(args["output"], exist_ok=True)
if args["vis"]!="":
    os.makedirs(args["vis"], exist_ok=True) 

for path in tqdm(imgs, total=len(imgs)):
    image = cv2.imread(path)
    H, W = image.shape[0], image.shape[1]
    rects = detector(image, 1)

    lmks = None
    face_cnt = 0

    # loop over the face detections
    for (i, rect) in enumerate(rects):
        # Only extract one face per image
        if face_cnt >= 1: break

        # determine the facial landmarks for the face region, then convert the facial landmark (x, y)-coordinates to a NumPy array
        shape = predictor(image, rect)
        lmks = lmk_to_np(shape)

        if np.sum(lmks < 0) > 0 or np.sum(lmks >= H) > 0 or np.sum(lmks >= W) > 0: 
            continue
        else:
            face_cnt += 1
            
        
        if args["lmk5p"]:
            lmks = extract_5p(lmks)

        if args["vis"]!="":
            # convert dlib's rectangle to a OpenCV-style bounding box [i.e., (x, y, w, h)], then draw the face bounding box
            x, y, w, h = rect_to_bb(rect)
            cv2.rectangle(image, (x, y), (x + w, y + h), (0, 255, 0), 2)
            # show the face number
            cv2.putText(image, "Face #{}".format(i + 1), (x - 10, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)
            # loop over the (x, y)-coordinates for the facial landmarks and draw them on the image
            for (x, y) in lmks:
                cv2.circle(image, (x, y), 3, (0, 0, 255), -1)
        
    # show the output image with the face detections + facial landmarks
    if args["vis"]!="":
        cv2.imwrite(os.path.join(args["vis"], os.path.basename(path).replace(".", "_output.")), image)
    
    if lmks is not None:
        save_lmks_to_file(lmks, os.path.join(args["output"], os.path.basename(path).split(".")[0]+".txt"))
        # print("lmks: ",lmks)
```

Hope this helps.

**Comment by YEYISHENG** [comment]
> I use MTCNN to do it, like the docs suggested (you can also use dlib). you can pip install it (make sure you also have opencv-python) you will also need nvidia dlls to make use of gpu acceleration but its not required
> 
> This is how I did it, it works on jpgs only, but you can alter it I made this for use in a video, so there is an if else there to reuse previous frames if the prediction is poor on current frame, just remove it to use on arbitrary images. call it in a cmd line or batch to generate the txts
> 
> ```
> import os
> import re
> import math
> os.add_dll_directory(os.getcwd())
> 
> import argparse
> from mtcnn import MTCNN
> import cv2
> 
> def find_between( s, first, last ):
>     try:
>         start = s.index( first ) + len( first )
>         end = s.index( last, start )
>         return s[start:end]
>     except ValueError:
>         return ""
> 
> def main(args):
>     #img = cv2.cvtColor(cv2.imread("ivan.jpg"), cv2.COLOR_BGR2RGB)
>     detector = MTCNN()
> 
> 
>     directory = os.path.abspath(args.image_folder)
>     totals = len(os.listdir(directory))
>     j = 0
>     for file in os.listdir(directory):
>          filename = os.path.join(directory, file)
>          if filename.endswith(".jpg"):
>              img = cv2.cvtColor(cv2.imread(filename), cv2.COLOR_BGR2RGB)
>              detect = detector.detect_faces(img)
>              confidence = detect[0]['confidence']
>              bbox =  detect[0]['box']
>              #print(totals)
>              if j < 1: print("Detection progress: " + str(round((j/totals)*100,2)) + "%")
>              if float(confidence) > 0.95 or j < 1:
>                  Leye = find_between(str(detect), '\'left_eye\': (', ')').replace(', ', '\t')
>                  Reye = find_between(str(detect), '\'right_eye\': (', ')').replace(', ', '\t')
>                  nose = find_between(str(detect), '\'nose\': (', ')').replace(', ', '\t')
>                  Lmouth = find_between(str(detect), '\'mouth_left\': (', ')').replace(', ', '\t')
>                  Rmouth = find_between(str(detect), '\'mouth_right\': (', ')').replace(', ', '\t')
>                  centerX = (float(bbox[0])+(float(bbox[2])/2.0)) #center X
>                  centerY = (float(bbox[1])+(float(bbox[3])/2.0)) #center Y
>                  LeyeB = Leye
>                  ReyeB = Reye
>                  noseB = nose
>                  LmouthB = Lmouth
>                  RmouthB = Rmouth
>                  centerXB = centerX
>                  centerYB = centerY
>              else:
>                  print('low confidence')
>                  Leye = LeyeB
>                  Reye = ReyeB
>                  nose = noseB
>                  Lmouth = LmouthB
>                  Rmouth = RmouthB
>                  centerX = centerXB
>                  centerY = centerYB
>              #print(Leye + '\n' + Reye + '\n' + nose + '\n' + Lmouth + '\n' + Rmouth)
>              f = open(os.path.join(directory, 'detections\\', file.replace('.jpg', '.txt')), "w")
>              f.write(Leye + '\n' + Reye + '\n' + nose + '\n' + Lmouth + '\n' + Rmouth)
>              f.close()
>              f2 = open(os.path.join(directory, 'detections\\', file.replace('.jpg', '.center')), "w")
>              f2.write(str(centerX) + '\n' + str(centerY))
>              f2.close()
>              j+=1
>              print("Detection progress: " + str(round((j/totals)*100,2)) + "%")
> 
> 
> 
>              continue
>              #break
>          else:
>              continue
> 
> 
> if __name__ == '__main__':
>     parser = argparse.ArgumentParser(description='Detect Faces')
>     parser.add_argument('-i', '--image_folder', type=str, default='configs/')
> 
> 
>     args = parser.parse_args()
>     main(args)
> ```

Can you tell me what should I do with your code?

**Comment by adevra** [comment]
> 

Thank you, it works perfectly👌
