### ISSUE TITLE
Error C7528: OpenGL reserves names starting with 'gl_': gl_PrimitiveID

### ISSUE THREAD

**Issue by geek0075** [sicxu/Deep3DFaceRecon_pytorch#86]
Hi,

I got the following exception trying to run:

$ python test.py --name=model1 --epoch=20 --img_folder=./datasets/mydata

This returns an error:

Error C7528: OpenGL reserves names starting with 'gl_': gl_PrimitiveID
Error C2003: Incompatible options for Link

Has anyone else experienced this? I am running on Windows with NVIDIA GeForce 3090.

Kind Regards.

**Comment by geek0075** [comment]
My Nvidia Driver Version:

Driver Provider: NVIDIA
Driver Version: 30.0.15.1179
Driver Date: 2/10/2022
Digital Signer: Microsoft Windows Hardware Compatibility Publisher

The error in more detail:

Model [FaceReconModel] was created
loading the model from ./checkpoints\model1\epoch_20.pth
0 ./datasets/biden512\0000001.jpg
[I D:\anaconda3\envs\deep3d_pytorch\lib\site-packages\nvdiffrast\common\glutil.cpp:119] Creating GL context for Cuda device 0
[I D:\anaconda3\envs\deep3d_pytorch\lib\site-packages\nvdiffrast\common\glutil.cpp:127] Selecting device with PCI bus id 000:01:00.0 - success
[I D:\anaconda3\envs\deep3d_pytorch\lib\site-packages\nvdiffrast\common\glutil.cpp:164] WGL OpenGL context (hdc: 0x81010f36, hglrc: 0x00010000)
[I D:\anaconda3\envs\deep3d_pytorch\lib\site-packages\nvdiffrast\common\rasterize.cpp:91] OpenGL version reported as 4.6

Traceback (most recent call last):
  File "test.py", line 74, in <module>
    main(0, opt, opt.img_folder)
  File "test.py", line 64, in main
    model.test()            # run inference
  File "D:\kay_taiwo\deep3d\Deep3DFaceRecon_pytorch\models\base_model.py", line 162, in test self.forward()
  File "D:\kay_taiwo\deep3d\Deep3DFaceRecon_pytorch\models\facerecon_model.py", line 139, in forward
    self.pred_vertex, self.facemodel.face_buf, feat=self.pred_color)
  File "D:\anaconda3\envs\deep3d_pytorch\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\kay_taiwo\deep3d\Deep3DFaceRecon_pytorch\util\nvdiffrast.py", line 58, in forward
    self.glctx = dr.RasterizeGLContext(device=device)
  File "D:\anaconda3\envs\deep3d_pytorch\lib\site-packages\nvdiffrast\torch\ops.py", line 151, in __init__
    self.cpp_wrapper = _get_plugin().RasterizeGLStateWrapper(output_db, mode == 'automatic', cuda_device_idx)
RuntimeError: glLinkProgram() failed:
Fragment info
-------------
0(2) : error C7528: OpenGL reserves names starting with 'gl_': gl_PrimitiveID
(0) : error C2003: Incompatible options for link

**Comment by fuyuntt** [comment]
I also encountered this problem. delete all the `in int gl_*` build-in variables in `rasterize.cpp`, it works for me.

**Comment by WangJYao** [comment]
Can you tell me exactly what to do

**Comment by geek0075** [comment]
If you follow along with 'Installation' section in this repo: https://github.com/sicxu/Deep3DFaceRecon_pytorch. Instead of doing:

$ git clone https://github.com/sicxu/Deep3DFaceRecon_pytorch.git --recursive

do:

$ git clone https://github.com/sicxu/Deep3DFaceRecon_pytorch.git

then

$ cd Deep3DFaceRecon_pytorch
$ git clone https://github.com/NVlabs/nvdiffrast
$ cd nvdiffrast    # ./Deep3DFaceRecon_pytorch/nvdiffrast
$ pip install .

So install your own nvdiffrast. The nvdiffrast branch that is installed when you do --recursive is an old version and has been superseded.

Let me know if that works...

**Comment by WangJYao** [comment]
Thank you so much!
 I succeeded!

**Comment by geek0075** [comment]
Cool WangJYao. Enjoy...

**Comment by adevra** [comment]
> 

thanks a lot big time!
