### ISSUE TITLE
The size of tensor a (35709) must match the size of tensor b (53215)

### ISSUE THREAD

**Issue by ra1995** [sicxu/Deep3DFaceRecon_pytorch#89]
Hi, I am getting the following output for the command
python ./test.py --name='face_recon' --epoch=20 --img_folder='./datasets/examples'

----------------- Options ---------------
                add_image: True
               bfm_folder: BFM
                bfm_model: BFM_model_front.mat
                 camera_d: 10.0
                   center: 112.0
          checkpoints_dir: ./checkpoints
             dataset_mode: None
                 ddp_port: 12355
        display_per_batch: True
                    epoch: 20                                   [default: latest]
          eval_batch_nums: inf
                    focal: 1015.0
                  gpu_ids: 0
               img_folder: ./datasets/examples                  [default: examples]
                init_path: checkpoints/init_model/resnet50-0676ba61.pth
                  isTrain: False                                [default: None]
                    model: facerecon
                     name: face_recon
                net_recon: resnet50
                    phase: test
                   suffix:
                  use_ddp: False                                [default: True]
              use_last_fc: False
                  verbose: False
           vis_batch_nums: 1
               world_size: 1
                    z_far: 15.0
                   z_near: 5.0
----------------- End -------------------
loading init net_recon resnet50 from checkpoints/init_model/resnet50-0676ba61.pth
model [FaceReconModel] was created
loading the model from ./checkpoints\face_recon\epoch_20.pth
0 ./datasets/examples\000002.jpg
Traceback (most recent call last):
  File "./test.py", line 72, in <module>
    main(0, opt,opt.img_folder)
  File "./test.py", line 62, in main
    model.test()           # run inference
  File "C:\Users\Rishabh\Documents\Repos\face\OSTeC\3rdParty\Deep3DFaceRecon_pytorch\models\base_model.py", line 162, in test
    self.forward()
  File "C:\Users\Rishabh\Documents\Repos\face\OSTeC\3rdParty\Deep3DFaceRecon_pytorch\models\facerecon_model.py", line 137, in forward
    self.facemodel.compute_for_render(output_coeff)
  File "C:\Users\Rishabh\Documents\Repos\face\OSTeC\3rdParty\Deep3DFaceRecon_pytorch\models\bfm.py", line 303, in compute_for_render
    face_color = self.compute_color(face_texture, face_norm_roted, coef_dict['gamma'])
  File "C:\Users\Rishabh\Documents\Repos\face\OSTeC\3rdParty\Deep3DFaceRecon_pytorch\models\bfm.py", line 176, in compute_color
    face_color = torch.cat([r, g, b], dim=-1) * face_texture
RuntimeError: The size of tensor a (35709) must match the size of tensor b (53215) at non-singleton dimension 1

**Comment by LY-Donkey-Burger** [comment]
> 嗨，我得到以下命令 python ./test.py --name='face_recon' --epoch=20 --img_folder='./datasets/examples' 的输出
> 
> ----------------- 选项 --------------- add_image: True bfm_folder: BFM bfm_model: BFM_model_front.mat camera_d: 10.0 center: 112.0 checkpoints_dir: ./checkpoints dataset_mode: None ddp_port: 12355 display_per_batch: True epoch: 20 [default: latest] eval_batch_nums: inf focus : 1015.0 gpu_ids: 0 img_folder: ./datasets/examples [default: examples] init_path: checkpoints/init_model/resnet50 -0676ba61.pth isTrain: False [默认: None] 模型: facerecon 名称: face_recon net_recon: resnet50 阶段: test 后缀： use_ddp：False [默认：True] use_last_fc：False 详细：False vis_batch_nums：1 world_size：1 z_far：15.0 z_near：5.0 ----------------- End ---- --------------- 从 checkpoints/init_model/resnet50-0676ba61.pth 加载 init net_recon resnet50 模型 [FaceReconModel] 是 从 ./checkpoints\face_recon\epoch_20.pth 0 加载模型创建的。 /datasets/examples\000002.jpg Traceback（最近一次调用最后）： 文件“./test.py”，第 72 行，在 main(0, opt,opt.img_folder) 文件“./test.py”，第 62 行, in main model.test() # 运行推理 文件“C:\Users\Rishabh\Documents\Repos\face\OSTeC\3rdParty\Deep3DFaceRecon_pytorch\models\base_model.py”，第 162 行，在测试 self.forward() 文件“C:\Users\Rishabh\Documents\Repos \face\OSTeC\3rdParty\Deep3DFaceRecon_pytorch\models\facerecon_model.py"，第 137 行，向前 self.facemodel.compute_for_render(output_coeff) 文件 "C:\Users\Rishabh\Documents\Repos\face\OSTeC\3rdParty\Deep3DFaceRecon_pytorch\ models\bfm.py"，第 303 行，在 compute_for_render face_color = self.compute_color(face_texture, face_norm_roted, coef_dict['gamma']) 文件“C:\Users\Rishabh\Documents\Repos\face\OSTeC\3rdParty\Deep3DFaceRecon_pytorch\ models\bfm.py"，第 176 行，在 compute_color face_color = torch.cat([r, g, b], dim=-1) * face_texture RuntimeError：张量 a (35709) 的大小必须与非单维 1 的张量 b (53215) 的大小相匹配

Hi，how did you solve the problem?
