### ISSUE TITLE
Outputs nothing in any folder, no clue how to fix.

### ISSUE THREAD

**Issue by GarnetSunset** [sicxu/Deep3DFaceRecon_pytorch#93]
````3f48889de02cdcb0/Deep3DFaceRecon_pytorch$ python test.py --name=a --epoch=20 --img_folder=./me
/home/a/anaconda3/envs/deep3d_pytorch/lib/python3.6/site-packages/kornia/augmentation/augmentation.py:1875: DeprecationWarning: GaussianBlur is no longer maintained and will be removed from the future versions. Please use RandomGaussianBlur instead.
  category=DeprecationWarning,
----------------- Options ---------------
                add_image: True
               bfm_folder: BFM
                bfm_model: BFM_model_front.mat
                 camera_d: 10.0
                   center: 112.0
          checkpoints_dir: ./checkpoints
             dataset_mode: None
                 ddp_port: 12355
        display_per_batch: True
                    epoch: 20                                   [default: latest]
          eval_batch_nums: inf
                    focal: 1015.0
                  gpu_ids: 0
               img_folder: ./me                                 [default: examples]
                init_path: checkpoints/init_model/resnet50-0676ba61.pth
                  isTrain: False                                [default: None]
                    model: facerecon
                     name: a                                    [default: face_recon]
                net_recon: resnet50
                    phase: test
                   suffix:
                  use_ddp: False                                [default: True]
              use_last_fc: False
                  verbose: False
           vis_batch_nums: 1
               world_size: 1
                    z_far: 15.0
                   z_near: 5.0
----------------- End -------------------
/home/a/anaconda3/envs/deep3d_pytorch/lib/python3.6/site-packages/torch/cuda/__init__.py:125: UserWarning:
NVIDIA GeForce RTX 3080 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the NVIDIA GeForce RTX 3080 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/```

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
model [FaceReconModel] was created
loading the model from ./checkpoints/a/epoch_20.pth
0 ./me/IMG20220728104454 - Copy.jpg
1 ./me/IMG20220728104454.jpg
````

Nothing gets outputted in either the results folder or in the images folder.

My command is ```python test.py --name=a --epoch=20 --img_folder=./me```

**Comment by Choons** [comment]
why was this closed? I have the exact same problem and there's no answer here

**Comment by GarnetSunset** [comment]
Fiaar point ill reopen it i just gave up

**Comment by endersaka** [comment]
I have exactly the same problem: no output. Does anybody have any clue?

**Comment by endersaka** [comment]
I think we forgot to prepare landmarks. Not sure but reading the `.\test.py` code it seems it loads and uses the landmarks so my guess is that they are not required only for training but also for test/demo. I am preparing a script to automatically calculate them with MTCNN.

**Comment by Choons** [comment]
Ah yeah, I read the code too. The "weakly supervised" part applies to the inference input images as well. Have to annotate those 5 points for your input image.

**Comment by adevra** [comment]
I'm using dLib instead of MTCNN, tried both but dLib was very straightforward. 

You have to create 5 point landmarks before running test.py
Algorithm automatically creates 68 points from those 5.

**Comment by endersaka** [comment]
> I'm using dLib instead of MTCNN, tried both but dLib was very straightforward.
> 
> You have to create 5 point landmarks before running test.py Algorithm automatically creates 68 points from those 5.

The point is that this is not documented anywhere and furthermore the script does not complain if it can't find the landmarks.

**Comment by adevra** [comment]
> 

it is documented, just not necessary to run a demo  
![image](https://user-images.githubusercontent.com/33916683/186174354-05fec71d-a756-48de-9af4-5837fc9837cc.png)

**Comment by endersaka** [comment]
> > 
> 
> it is documented, just not necessary to run a demo ![image](https://user-images.githubusercontent.com/33916683/186174354-05fec71d-a756-48de-9af4-5837fc9837cc.png)

Thanks for the clarification but I already read that part. I guessed it was required also for `test.py` (since the code actually loads the landmarks) but you say it is not. Therefore we (of those who experienced the problem) are stuck to the initial issue. Why does the test produce no output?

**Comment by adevra** [comment]
@endersaka
https://github.com/sicxu/Deep3DFaceRecon_pytorch/tree/master/datasets/examples/detections 
this is the folder where 5pts landmarks are created beforehand for the demo and yes, therefore you don't have to create 5pts landmarks to run test.py for example images. If you are not having any errors I'd suggest you to check your folder structure or start over fresh with the info you just got.

@GarnetSunset you get this error : _NVIDIA GeForce RTX 3080 with CUDA capability sm_86 is not compatible with the current PyTorch installation._ I'd suggest a clean install of cuda_10.2.89_441.22_win10 (I'm using this version with win11)

Other than that the process is very straightforward.

For anyone else,

**You don't have to create those 5pts landmarks to run test.py with this prompt:** 
`python test.py --name=<model_name> --epoch=20 --img_folder=./datasets/examples` 

**To run the test.py for your custom images with this prompt,**  
`python test.py --name=<model_name> --epoch=20 --img_folder=<folder_to_test_images>`
you have to generate 5points landmarks as suggested and documented in "Data Preparation" section.

**Comment by endersaka** [comment]
> @endersaka https://github.com/sicxu/Deep3DFaceRecon_pytorch/tree/master/datasets/examples/detections this is the folder where 5pts landmarks are created beforehand for the demo and yes, therefore you don't have to create 5pts landmarks to run test.py for example images. If you are not having any errors I'd suggest you to check your folder structure or start over fresh with the info you just got.

Though IMO, it should be made cristal clear that if anyone wants to use `test.py` on **custom images** he has to prepare the `detections` directory filled with landmarks. The paragraph "Data preparation" position made me think that it is not related to the `test.py` requirements in any ways.

Also the `test.py` script does not complain in any way if it does not find `detections` directory filled with landmarks. According to best practices in software development leaving the user without any feedback in case of error can be considered a poor software design.

**Comment by sicxu** [comment]
I have updated the test.py to output a hint about the missing of detection files.  Sorry for your inconvenience.
