### ISSUE TITLE
some  suggestion of environment

### ISSUE THREAD

**Issue by Dhaizei** [sicxu/Deep3DFaceRecon_pytorch#94]
if installing high cuda version ,there is a error. it is"Error C7528: OpenGL reserves names starting with 'gl_': gl_PrimitiveID
Error C2003: Incompatible options for Link"
we need to seek suitable nvdiffrast version,because here provided github code is old.
so we need to do following steps:
instead of doing:

$ git clone https://github.com/sicxu/Deep3DFaceRecon_pytorch.git --recursive

do:

$ git clone https://github.com/sicxu/Deep3DFaceRecon_pytorch.git

then

$ cd Deep3DFaceRecon_pytorch
$ git clone https://github.com/NVlabs/nvdiffrast
$ cd nvdiffrast # ./Deep3DFaceRecon_pytorch/nvdiffrast
$ pip install .
hope author to update code ,thanks.

**Comment by sicxu** [comment]
Thanks for your suggestion, I have updated the installation section in README.
