### ISSUE TITLE
question about 5-point detection

### ISSUE THREAD

**Issue by LY-Donkey-Burger** [sicxu/Deep3DFaceRecon_pytorch#96]
Hi, your work is fantastic. I found some datasets with ground truth, why not use the existing ground truth to carry out 5-point detection again?

**Comment by CS123n** [comment]
Good question!

**Comment by sicxu** [comment]
No particular reasons actually, we just detect all the dataset to get a unified definition for our convenience. You can use the original ground truth to process the data for your own purpose.
